In [3]:
import opportunity_constructs.stock_mr as mr
output_frame = mr.get_smrl_signal_frame()
stocks = output_frame['stocks']

print('Data success: ' + str(100*stocks['data_success'].sum()/len(stocks)))
stocks[stocks['rsi_success']==1]

Data success: 90.51094890510949

,adx7,adx_success,atr10,atr_percent10,atr_success,close_price,data_success,dollar_volume_success,file_success,ma150,price_success,rsi3,rsi_success,symbol,trend_success,volume_success
692,50.160133,1,4.808558,5.394851,1,82.75,1,1,1,66.619067,1,28.063056,1,NKTR,1,1
1674,47.230586,1,0.212192,5.991892,1,3.12,1,1,1,3.030933,1,24.126123,1,CVEO,1,1
3759,47.581086,1,0.412958,4.096929,1,9.35,1,1,1,8.711000,1,14.864985,1,WAIR,1,1
5989,51.429924,1,3.772968,4.065364,1,68.99,1,1,1,67.923300,1,20.621041,1,FISV,1,1

In [4]:
import opportunity_constructs.stock_mr as mr
output_frame = mr.get_smrs_signal_frame()
stocks = output_frame['stocks']

print('Data success: ' + str(100*stocks['data_success'].sum()/len(stocks)))
stocks[stocks['rsi_success']==1]

# sell 47 shares of  I

Data success: 90.51094890510949

,adx7,adx_success,atr10,atr_percent10,atr_success,close_price,data_success,file_success,price_success,rsi3,rsi_success,symbol,volume_success
5097,73.409795,1,1.003386,8.438422,1,14.02,1,1,1,93.707862,1,DRNA,1

In [6]:
stocks['close_price'].loc[stocks['rsi_success']==1].values[0]

10.02

In [14]:
import opportunity_constructs.stock_mrl as mrl
output_frame = mrl.import opportunity_constructs.stock_mrl as mrl
output_frame = mrl.get_signal_frame(settle_date=20180410)(settle_date=20180410)

In [15]:
stocks = output_frame['stocks']
stocks[stocks['rsi_success']==1]

,adx7,adx_success,atr10,atr_percent10,atr_success,close_price,data_success,dollar_volume_success,file_success,ma150,price_success,rsi3,rsi_success,symbol,trend_success,volume_success
278,47.965845,1,0.303165,9.629713,1,3.07,1,1,1,2.029824,1,14.834085,1,AMPE,1,1
1028,47.914496,1,0.557095,6.476821,1,8.20,1,1,1,6.374633,1,20.803129,1,RUN,1,1

In [6]:
import signals.stock_mr as smr
smr.get_stock_mrl_signals(symbol='LL',settle_date=20180419)

{'adx7': nan,
 'adx_success': 0,
 'atr10': nan,
 'atr_percent10': nan,
 'atr_success': 0,
 'close_price': 22.949999999999999,
 'data_success': 1,
 'dollar_volume_success': 1,
 'file_success': 1,
 'ma150': 29.216800000000053,
 'price_success': 1,
 'rsi3': nan,
 'rsi_success': 0,
 'symbol': 'LL',
 'trend_success': 0,
 'volume_success': 1}

In [21]:
import matplotlib.pyplot as plt

plt.plot(range(len(price_data.index)),price_data['close'],
         range(len(price_data.index)),price_data['adjusted_close'])
plt.grid()         
         
plt.show()

In [1]:
import opportunity_constructs.stock_mrl as mrl
output_frame = mrl.get_signal_frame(settle_date=20180418)

In [5]:
stocks = output_frame['stocks']
candidates = stocks[stocks['atr_success']==1]
candidates

,adx7,adx_success,atr_percent10,atr_success,close_price,data_success,dollar_volume_success,file_success,ma150,price_success,rsi3,rsi_success,symbol,trend_success,volume_success
102,59.468040,1,4.008514,1,32.60,1,1,1,26.541333,1,90.588366,0,OIS,1,1
114,50.117923,1,5.320499,1,81.45,1,1,1,67.391767,1,89.168695,0,ONCE,1,1
123,52.737218,1,17.713565,1,3.38,1,1,1,2.043731,1,90.290000,0,CNET,1,1
151,45.683036,1,8.313686,1,19.54,1,1,1,18.111667,1,56.365871,0,SPPI,1,1
244,47.127932,1,5.472562,1,14.50,1,1,1,12.678500,1,71.842590,0,ALDR,1,1
265,49.194608,1,11.434728,1,4.34,1,1,1,3.577873,1,24.346769,1,ZSAN,1,1
336,62.809917,1,4.950843,1,15.40,1,1,1,13.686467,1,96.193604,0,RDC,1,1
454,46.327377,1,5.127623,1,3.09,1,1,1,2.357800,1,99.225438,0,EXK,1,1
466,59.483498,1,4.148051,1,29.25,1,1,1,22.000133,1,95.952797,0,VNOM,1,1
685,49.216201,1,5.663485,1,22.79,1,1,1,20.809133,1,88.817214,0,UNT,1,1
822,51.107100,1,5.205356,1,6.97,1,1,1,6.596600,1,97.493331,0,FI,1,1
1126,54.267594,1,4.952823,1,35.97,1,1,1,27.579533,1,85.597022,0,HOME,1,1
1206,71.253223,1,12.604825,1,9.07,1,1,1,4.322867,1,96.875055,0,I,1,1
1308,56.034669,1,4.166739,1,10.70,1,1,1,4.712000,1,37.060560,0,ONE,1,1
1543,46.087959,1,7.871059,1,12.99,1,1,1,10.352533,1,54.912492,0,CBAY,1,1
1578,60.824572,1,5.844351,1,18.52,1,1,1,18.154433,1,91.315816,0,CRZO,1,1
2026,59.039893,1,4.090822,1,17.55,1,1,1,14.454000,1,91.924724,0,AMC,1,1
2175,53.932285,1,11.473635,1,3.88,1,1,1,3.740600,1,53.723134,0,RIGL,1,1
2273,58.830698,1,4.516222,1,39.37,1,1,1,21.880067,1,88.517946,0,WLL,1,1
2314,55.308790,1,5.967234,1,3.67,1,1,1,2.914733,1,41.708113,0,SENS,1,1
2359,53.496196,1,4.604516,1,10.65,1,1,1,10.301167,1,93.401813,0,AROC,1,1
2386,47.429275,1,8.596780,1,12.50,1,1,1,6.716833,1,81.417248,0,VCEL,1,1
2625,51.020159,1,5.269096,1,21.76,1,1,1,20.386133,1,92.379549,0,SM,1,1
2760,66.788929,1,7.543853,1,24.04,1,1,1,16.112133,1,97.369011,0,CRC,1,1
2876,47.308872,1,5.188646,1,26.36,1,1,1,24.490933,1,83.448789,0,FLXN,1,1
2918,50.360330,1,5.975147,1,4.79,1,1,1,4.269333,1,97.848057,0,NE,1,1
2921,48.360474,1,7.414848,1,29.78,1,1,1,18.624533,1,88.371552,0,CVNA,1,1
3025,76.536796,1,9.006784,1,7.56,1,1,1,2.977808,1,80.311298,0,TNDM,1,1
3340,50.409892,1,5.407653,1,18.87,1,1,1,15.272733,1,45.654575,0,XON,1,1
3682,52.076001,1,10.809575,1,2.89,1,1,1,0.835480,1,95.149247,0,NIHD,1,1
3901,45.396483,1,5.893137,1,8.96,1,1,1,8.861267,1,79.489959,0,FTR,1,1
4061,58.371826,1,5.450357,1,2.91,1,1,1,2.193533,1,98.509421,0,AXAS,1,1
4126,63.053370,1,4.504525,1,59.40,1,1,1,47.774200,1,99.436801,0,AA,1,1
4164,72.728033,1,4.915198,1,24.30,1,1,1,16.426600,1,98.531265,0,WRD,1,1
4166,55.311377,1,5.892864,1,6.01,1,1,1,5.477867,1,99.052102,0,ESV,1,1
4250,55.809915,1,5.465363,1,15.07,1,1,1,9.770700,1,47.739815,0,FOSL,1,1
4502,70.197126,1,5.306769,1,209.60,1,1,1,113.725933,1,67.377961,0,AVXS,1,1
4556,65.089360,1,4.060380,1,22.75,1,1,1,18.366533,1,81.851442,0,PAY,1,1
4706,55.328394,1,6.384976,1,4.14,1,1,1,3.631833,1,83.919157,0,VSTM,1,1
4752,53.849516,1,7.185318,1,11.45,1,1,1,9.945733,1,58.863040,0,QNST,1,1
5135,54.337143,1,4.646933,1,4.30,1,1,1,3.898133,1,91.501836,0,IPI,1,1
5419,56.718153,1,4.391009,1,10.26,1,1,1,9.338933,1,75.985052,0,CVE,1,1
5530,47.181483,1,4.203886,1,12.67,1,1,1,11.736033,1,95.675102,0,ECA,1,1
5585,52.721181,1,4.362819,1,12.11,1,1,1,9.282333,1,98.591535,0,QEP,1,1
5662,51.553875,1,4.745473,1,17.10,1,1,1,14.805667,1,79.660400,0,TISI,1,1
5781,59.733988,1,4.992328,1,19.53,1,1,1,16.221267,1,93.860873,0,DO,1,1
5883,50.697909,1,4.424487,1,8.30,1,1,1,6.910167,1,91.803248,0,BGFV,1,1
5950,55.003874,1,7.341168,1,19.80,1,1,1,15.832867,1,70.505569,0,ABEO,1,1
5990,56.183163,1,4.804924,1,12.43,1,1,1,10.319667,1,96.661966,0,RIG,1,1
6078,52.667538,1,14.523839,1,8.77,1,1,1,6.421033,1,58.358862,0,NETE,1,1